apiVersion: v1
kind: Pod
metadata:
  name: multi-c-pod
  labels:
    role: multic
    app: nginx
    project: demo
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
  - name: cache
    image: memcached:alpine
    ports:
    - containerPort: 11211

