apiVersion: v1
kind: Pod
metadata:
  name: craftista-frontend
  labels:
    role: frontend
    project: craftista
    version: v1
spec:
  containers:
  - name: frontend
    image: schoolofdevops/craftista-frontend:v1
    ports:
    - containerPort: 3000
    resources:
      limits:
        cpu: "200m"
        memory: "138Mi"
      requests:
        cpu: "40m"
        memory: "56Mi"

